ident = { XID_START ~ XID_CONTINUE* }
key = { "." ~ ident }
int = { "-"? ~ NUMBER+ }
string = { "\"" ~ (!("\"") ~ ANY)* ~ "\""}
subscript = { "[" ~ ( string | int ) ~ "]" }
full_range = { "[]" }
range = { "[" ~ int ~ ":" ~ int ~ "]" }
range_to = { "[:" ~ int ~ "]" }
range_from = { "[" ~ int ~ ":]" }
segment = _{ key | subscript | full_range | range | range_to | range_from }
identity = { "." }

selector = { SOI ~ (segment+ | identity) ~ EOI }